scan_filter_chain:

# Filter out East wall
- name: walls
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: map
    min_x: 0.05
    max_x: 3.5
    min_y: 0.05
    max_y: 5.0
    min_z: -10.0
    max_z: 10.0
    invert: true