# Controller configuration for Logitech Gamepad F310

axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 1.0

enable_button: 4  # LB
enable_turbo_button: -1  # Disabled