point_cloud_topic: "/perception_cloud"
map_frame_id: "map"
robot_base_frame_id: "perception_frame"
robot_pose_with_covariance_topic: "/flagPose"
robot_pose_cache_size: 200
track_point_frame_id: "perception_frame"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
